version: '3.9'
services:
  python:
    # M1Macでないため不要
    # platform: linux/amd64
    container_name: python
    build: .
    volumes:
      - type: bind
        source: "./app"
        target: "/app"
    working_dir: /app
    ports:
      - "5001:5000"
      - "8080:8000"
    tty: true
